import importlib


def _dispatch(module_name: str, func_name: str = "cmd"):
    def _runner(args):
        module = importlib.import_module(module_name)
        getattr(module, func_name)(args)
    return _runner


def _add_io_args(p):
    p.add_argument("-i", "--input", required=True, help="Input file (TSV)")
    p.add_argument("-o", dest="output", help="Output file (default: stdout)")
    p.add_argument("--sep", default=None, help="Column separator (default: tab)")


def register_subparser(subparsers):
    math_parser = subparsers.add_parser("math", help="Mathematical and statistical tools")
    math_sub = math_parser.add_subparsers(dest="math_cmd")
    math_parser.set_defaults(_group_parser=math_parser)

    p = math_sub.add_parser("statistics", help="Descriptive statistics of a numeric column")
    _add_io_args(p)
    p.add_argument("-c", "--col", default="1", help="Column name or index (default: 1)")
    p.set_defaults(func=_dispatch("jsrc.math.statistics"))

    p = math_sub.add_parser("correlation", help="Pearson / Spearman correlation")
    _add_io_args(p)
    p.add_argument("-c", "--col", nargs=2, required=True, metavar=("COL1", "COL2"), help="Two column names or indices")
    p.add_argument("-m", "--method", choices=["pearson", "spearman", "both"], default="both", help="Correlation method")
    p.set_defaults(func=_dispatch("jsrc.math.correlation"))

    p = math_sub.add_parser("regression", help="Linear or polynomial regression")
    _add_io_args(p)
    p.add_argument("-c", "--col", nargs=2, required=True, metavar=("X", "Y"), help="X and Y column names or indices")
    p.add_argument("-d", "--degree", type=int, default=1, help="Polynomial degree (default: 1)")
    p.set_defaults(func=_dispatch("jsrc.math.regression"))

    p = math_sub.add_parser("ttest", help="Student's t-tests")
    _add_io_args(p)
    p.add_argument("-c", "--col", nargs="+", required=True, help="One (vs mu) or two columns")
    p.add_argument("--mu", type=float, default=0, help="Population mean for one-sample test")
    p.add_argument("--paired", action="store_true", help="Paired t-test (two columns)")
    p.add_argument("--equal-var", action="store_true", help="Assume equal variance (Welch otherwise)")
    p.set_defaults(func=_dispatch("jsrc.math.ttest"))

    p = math_sub.add_parser("chisquare", help="Chi-squared test for independence or goodness-of-fit")
    p.add_argument("-i", "--input", help="Input file (TSV) for contingency table test")
    p.add_argument("-o", dest="output", help="Output file (default: stdout)")
    p.add_argument("--sep", default=None, help="Column separator (default: tab)")
    p.add_argument("--observed", nargs="+", type=float, help="Observed counts for goodness-of-fit")
    p.add_argument("--expected", nargs="+", type=float, help="Expected counts for goodness-of-fit")
    p.add_argument("-c", "--col", nargs=2, metavar=("COL1", "COL2"), help="Two columns for contingency table")
    p.set_defaults(func=_dispatch("jsrc.math.chisquare"))

    p = math_sub.add_parser("anova", help="One-way ANOVA")
    _add_io_args(p)
    p.add_argument("-g", "--group-col", required=True, help="Group/class column")
    p.add_argument("-v", "--value-col", required=True, help="Value column")
    p.set_defaults(func=_dispatch("jsrc.math.anova"))

    p = math_sub.add_parser("nonparametric", help="Mann-Whitney U / Wilcoxon signed-rank tests")
    _add_io_args(p)
    p.add_argument("-c", "--col", nargs=2, required=True, metavar=("COL1", "COL2"), help="Two columns")
    p.add_argument("--paired", action="store_true", help="Wilcoxon signed-rank (paired)")
    p.set_defaults(func=_dispatch("jsrc.math.nonparametric"))

    p = math_sub.add_parser("distribution", help="PDF / CDF queries for standard distributions")
    p.add_argument("-o", dest="output", help="Output file (default: stdout)")
    p.add_argument("--dist", required=True, choices=["normal", "t", "f", "chi2"], help="Distribution name")
    p.add_argument("--x", type=float, required=True, help="Quantile")
    p.add_argument("--df1", type=float, default=None, help="Degrees of freedom 1")
    p.add_argument("--df2", type=float, default=None, help="Degrees of freedom 2")
    p.add_argument("--pdf", action="store_true", help="Show PDF value")
    p.set_defaults(func=_dispatch("jsrc.math.distribution"))

    p = math_sub.add_parser("kmeans", help="K-means clustering")
    _add_io_args(p)
    p.add_argument("-k", type=int, default=3, help="Number of clusters (default: 3)")
    p.add_argument("--max-iter", type=int, default=100, help="Max iterations")
    p.set_defaults(func=_dispatch("jsrc.math.kmeans"))

    p = math_sub.add_parser("hcluster", help="Hierarchical clustering")
    _add_io_args(p)
    p.add_argument("-m", "--method", choices=["single", "complete", "average"], default="average", help="Linkage method")
    p.add_argument("-k", type=int, default=None, help="Number of clusters to output")
    p.set_defaults(func=_dispatch("jsrc.math.hcluster"))

    p = math_sub.add_parser("knn", help="K-nearest neighbors (predict from training + test)")
    p.add_argument("--train", required=True, help="Training file (TSV)")
    p.add_argument("--test", required=True, help="Test file (TSV)")
    p.add_argument("-k", type=int, default=3, help="Number of neighbors (default: 3)")
    p.add_argument("--target-col", required=True, help="Target column name")
    p.add_argument("--regression", action="store_true", help="Regression (mean) instead of classification (vote)")
    p.add_argument("-o", dest="output", help="Output file for predictions")
    p.set_defaults(func=_dispatch("jsrc.math.knn"))

    p = math_sub.add_parser("naivebayes", help="Gaussian Naive Bayes classifier")
    p.add_argument("--train", required=True, help="Training file (TSV)")
    p.add_argument("--test", required=True, help="Test file (TSV)")
    p.add_argument("--target-col", required=True, help="Target column name")
    p.add_argument("-o", dest="output", help="Output file for predictions")
    p.set_defaults(func=_dispatch("jsrc.math.naivebayes"))

    p = math_sub.add_parser("decisiontree", help="Decision tree classifier/regressor")
    p.add_argument("--train", required=True, help="Training file (TSV)")
    p.add_argument("--test", required=True, help="Test file (TSV)")
    p.add_argument("--target-col", required=True, help="Target column name")
    p.add_argument("--max-depth", type=int, default=5, help="Max tree depth")
    p.add_argument("--min-samples", type=int, default=2, help="Min samples to split")
    p.add_argument("--regression", action="store_true", help="Regression (variance reduction) instead of classification")
    p.add_argument("-o", dest="output", help="Output file for predictions")
    p.add_argument("--print-tree", action="store_true", help="Print the decision tree")
    p.set_defaults(func=_dispatch("jsrc.math.decisiontree"))

    p = math_sub.add_parser("randomforest", help="Random forest classifier/regressor")
    p.add_argument("--train", required=True, help="Training file (TSV)")
    p.add_argument("--test", required=True, help="Test file (TSV)")
    p.add_argument("--target-col", required=True, help="Target column name")
    p.add_argument("-n", "--n-trees", type=int, default=50, help="Number of trees")
    p.add_argument("--max-depth", type=int, default=5, help="Max tree depth")
    p.add_argument("--regression", action="store_true", help="Regression instead of classification")
    p.add_argument("-o", dest="output", help="Output file for predictions")
    p.set_defaults(func=_dispatch("jsrc.math.randomforest"))

    p = math_sub.add_parser("gbm", help="Gradient boosting machine (regression)")
    p.add_argument("--train", required=True, help="Training file (TSV)")
    p.add_argument("--test", required=True, help="Test file (TSV)")
    p.add_argument("--target-col", required=True, help="Target column name")
    p.add_argument("-n", "--n-trees", type=int, default=50, help="Number of boosting iterations")
    p.add_argument("--lr", "--learning-rate", type=float, default=0.1, dest="lr", help="Learning rate")
    p.add_argument("--max-depth", type=int, default=3, help="Max tree depth of each stump")
    p.add_argument("-o", dest="output", help="Output file for predictions")
    p.set_defaults(func=_dispatch("jsrc.math.gbm"))

    p = math_sub.add_parser("survival", help="Kaplan-Meier estimator and Log-rank test")
    p.add_argument("-i", "--input", required=True, help="Input file (TSV)")
    p.add_argument("--sep", default=None, help="Column separator (default: tab)")
    p.add_argument("--time-col", required=True, help="Column for survival time")
    p.add_argument("--event-col", required=True, help="Column for event indicator (1=event, 0=censored)")
    p.add_argument("--group-col", help="Group column for Log-rank test")
    p.add_argument("-o", dest="output", help="Output file for survival table")
    p.set_defaults(func=_dispatch("jsrc.math.survival"))

    p = math_sub.add_parser("simulate", help="ODE model simulations (SIR, Lotka-Volterra, PK, etc.)")
    p.add_argument("-m", "--model", required=True, choices=["sir", "lotkavolterra", "pk1", "emax", "gompertz", "logistic"],
                   help="Model to simulate")
    p.add_argument("--params", nargs="+", type=float, required=True, help="Model parameters")
    p.add_argument("--tmax", type=float, default=100, help="Simulation time")
    p.add_argument("--dt", type=float, default=0.1, help="Time step")
    p.add_argument("--init", nargs="+", type=float, default=None, help="Initial conditions")
    p.add_argument("-o", dest="output", help="Output file")
    p.set_defaults(func=_dispatch("jsrc.math.simulate"))

    p = math_sub.add_parser("montecarlo", help="Monte Carlo simulation")
    p.add_argument("-n", "--n-samples", type=int, default=10000, help="Number of samples")
    p.add_argument("--mean", type=float, default=0.0, help="Mean of normal distribution")
    p.add_argument("--sd", type=float, default=1.0, help="Std dev of normal distribution")
    p.add_argument("--stat", choices=["mean", "median", "sd", "min", "max"], default="mean",
                   help="Statistic to compute")
    p.add_argument("-o", dest="output", help="Output file")
    p.set_defaults(func=_dispatch("jsrc.math.montecarlo"))

    p = math_sub.add_parser("mcmc", help="Metropolis-Hastings MCMC sampling")
    p.add_argument("-n", "--n-samples", type=int, default=5000, help="Number of MCMC iterations")
    p.add_argument("--burnin", type=int, default=500, help="Burn-in iterations")
    p.add_argument("--init", type=float, default=0.0, help="Initial value for chain")
    p.add_argument("--prior-mean", type=float, default=0.0, help="Prior mean")
    p.add_argument("--prior-sd", type=float, default=10.0, help="Prior SD")
    p.add_argument("--data", nargs="+", type=float, default=None, help="Observed data")
    p.add_argument("--proposal-sd", type=float, default=0.5, help="Proposal step SD")
    p.add_argument("-o", dest="output", help="Output file")
    p.set_defaults(func=_dispatch("jsrc.math.mcmc"))

    p = math_sub.add_parser("hmm", help="Hidden Markov Model (forward/backward/Viterbi)")
    p.add_argument("--states", nargs="+", required=True, help="State names")
    p.add_argument("--observations", nargs="+", required=True, help="Observation sequence")
    p.add_argument("--trans-probs", nargs="+", type=float, required=True, help="Transition matrix (row-major)")
    p.add_argument("--emit-probs", nargs="+", type=float, required=True, help="Emission matrix (row-major)")
    p.add_argument("--start-probs", nargs="+", type=float, required=True, help="Start probabilities")
    p.add_argument("--task", choices=["forward", "backward", "viterbi"], default="viterbi", help="Task")
    p.add_argument("-o", dest="output", help="Output file")
    p.set_defaults(func=_dispatch("jsrc.math.hmm"))
